DuckDuckStudio/yazicbs.github.io

- Articles/Blogs.html
> update new blog test

- Articles/Blogs.html
[Pref] 可以使用`<details>`与`<summary>`标签来折叠内容 #27
> pref: 使用`<details>`与`<summary>`标签来折叠内容 (#27)

- zh_cn/index.html
Fix #33 
@fjwxzde run test --1
> fix:修复地区识别出错 (#33)

- .action_scripts/check-local-paths.js
- .github/workflows/check-local-paths.yml
- .gitignore
- 404.html
> [TEST] 检查代码中的本地路径

- Tools/Fufu_Tools/index.html
- Tools/Fufu_Tools/versions/index.html
> docs: 更新芙芙工具箱文档

- .action_scripts/link_checker.py
- .github/workflows/check_url_visit.yml
- Tools/Fufu_Tools/wiki/error/index.html
- Tools/Fufu_Tools/wiki/index.html
- Tools/Fufu_Tools/wiki/通用/index.html
> Sync changes

- en/404.html
- jp/404.html
> Auto: 修改建议

- .github/PULL_REQUEST_TEMPLATE.md
- sitemap.xml
> [Auto] Update sitemap 20241027T0935

- sitemap.xml
> [Auto] Update sitemap 20241029T1314

- sitemap.xml
@fjwxzde run test
@fjwxzde auto approve
---
> Sync change(s) to location branch.

- Tools/Fufu_Tools/index.html
> 更新芙芙工具箱最新版本

- .gitignore
- Interesting/index.html
- Interesting/鸭子活了人几岁/index.html
- Interesting/鸭子活了人几岁/main.js
- Interesting/鸭子活了人几岁/style.css
> Interesting: 我家鸭子活了人几岁

- Interesting/vacation_countdown/样式.css
- Interesting/鸭子活了人几岁/index.html
- Interesting/鸭子活了人几岁/main.js
- Interesting/鸭子活了人几岁/style.css
> pref: 移动设备优化

- sitemap.xml
> Update sitemap 2024/11/11 22:46

- Interesting/鸭子活了人几岁/main.js
> pref: 优化 我家嘎嘎活了人几岁 

- .action_scripts/JavaScript/generate-sitemap.mjs
- .github/workflows/check_url_visit.yml
- .github/workflows/generate-sitemap.yml
> fix: Fix test error

- sitemap.xml
Created through the [workflow](https://github.com/DuckDuckStudio/yazicbs.github.io/actions/runs/11810955947).
> [2024/11/13 05:14] Auto update sitemap

- sitemap.xml
Created through the [workflow](https://github.com/DuckDuckStudio/yazicbs.github.io/actions/runs/11815934366).
> [2024/11/13 11:03] Auto update sitemap

- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/preference_adjective.yml
> feat: ✨优化议题模板

- zh_cn/debug.html
> feat🚀: 对于手机测试的控制台页面

- .github/dependabot.yml
> 更新 dependabot.yml

- Tools/Fufu_Tools/index.html
> 更新芙芙工具箱开发工具包预览版版本链接至2025.01.02.2300

- Tools/Fufu_Tools/index.html
> chore(license): 更新芙芙工具箱许可文件信息

- Tools/Fufu_Tools/index.html
- sitemap.xml
> chore(fft-docs): Bump version to v1.3.6

- Tools/Fufu_Tools/index.html
> docs: 更新开发工具包版本

- Tools/Fufu_Tools/wiki/各个工具文档/index.html
- Tools/Fufu_Tools/wiki/各个工具文档/实验性小工具/index.html
> docs: 更新芙芙工具箱各个工具和实验性工具文档

- Tools/Fufu_Tools/wiki/index.html
- Tools/Fufu_Tools/wiki/各个工具文档/index.html
- Tools/Fufu_Tools/wiki/各个工具文档/定时关机/index.html
> docs: 芙芙工具箱定时关机说明文档

- zh_cn/debug.html
- zh_cn/index.html
> pref: 将你好【某地】的位置范围扩大到省 #291

- .github/workflows/check-local-paths.yml
- .github/workflows/check_url_visit.yml
- .github/workflows/generate-sitemap.yml
- .github/workflows/handle_auto_merge_labels.yml
- 404.html
- en/404.html
- jp/404.html
> fix(CodeQL): 修复一些 CodeQL 扫描错误

- zh_cn/js/games/simplified/guess_number.js
之前是 warn。
自动总结（实验性）：将猜数字游戏的简化版的提示消息等级从 **警告** 改为 **信息**。
---
> chore(logs): 修改简化版猜数字 js 的警告等级为 log
